apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minemeld
  labels:
        app: minemeld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minemeld
  template:
    metadata:
      name: minemeld
      labels:
        app: minemeld      
    spec:
      containers:
      - name: minemeld
        image: mterron/minemeld
        ports:
        - containerPort: 443
---    
apiVersion: v1
kind: Service
metadata:
  name: minemeld
  labels:
    app: minemeld
spec:
  type: LoadBalancer
  ports:
    - port: 443
  selector:
    app: minemeld